### ISSUE TITLE
What's actually a dofus proxy ?

### ISSUE THREAD

**Issue by shiglet** [jordanamr/D1Proxy#2]
?

**Comment by jordanamr** [comment]
This is a MITM Proxy for the videogame Dofus (Version 1.29.1/1.30.0) that allow semi-automation features, network & maps sniffing and much more. This is mostly a tool for developers

**Comment by shiglet** [comment]
I have already tryed to contact you on tweeter but i think your dm aren't activated.

Or am i wrong ?

Thank you, it can be usefull for me. I'm trying to update an old dofus bot done in c#. Yours, isn't actually a bot but a tool ? isn't it ?

Thank you.
